server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://lakePayPostgres:5432/lakepay_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: chatService

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: chat-service

token:
  signing:
    key: DajeRi8ErJlN9EjIfgr8PJwkagj8j4XI3ePoANmysKL

#TODO: Disable on prod
debug: true

