server:
  port: 8082

spring:
  datasource:
    # Change db credentials before merging to dev
    url: jdbc:postgresql://localhost:5432/chat_db
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

token:
  signing:
    key: DajeRi8ErJlN9EjIfgr8PJwkagj8j4XI3ePoANmysKL

debug: true

