spring:
  application:
    name: adService

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:postgresql://lakePayPostgres:5432/lakepay_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8780

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

token:
  signing:
    key: q1o7M1V+7R1Qyx4e0y1m8qLC+xRP0U8UwK0QH5Xt7lQ=