server:
  port: 7890

spring:
  datasource:
      url: jdbc:postgresql://lakepay:5432
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
