spring:
  application:
    name: paymentService

  datasource:
    url: ${DB_URL:jdbc:jdbc:postgresql://lakePayPostgres:5432/lakepay_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DB_MODE:false}

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    redis:
      host: ${SPRING_REDIS_HOST:lakePayRedis}
      port: ${SPRING_REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: payment-service

crypto-bot:
  api: https://testnet-pay.crypt.bot/api
  token: ${CRYPTO_BOT_TOKEN}

token:
  signing:
    key: ${JWT_SIGNING_KEY} # JWT signing key
    lifetime: ${JWT_TOKEN_LIFETIME}

server:
  port: 8083
