server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:jdbc:postgresql://lakePayPostgres:5432/lakepay_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DB_MODE}

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  application:
    name: userService

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

crypto-bot:
  api-url: https://testnet-pay.crypt.bot/api/
  api-token: ${CRYPTO_BOT_TOKEN}

token:
  signing:
    key: ${JWT_SIGNING_KEY} # JWT signing key
    lifetime: ${JWT_TOKEN_LIFETIME}
  telegram:
    bot: ${TG_BOT_TOKEN} # Authentication Telegram bot token

debug: ${DEBUG_MODE}