server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://lakePayPostgres:5432/lakepay_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  application:
    name: userService

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

