server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://lakePayPostgres:5432/lakepay_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  application:
    name: userService

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

crypto-bot:
  api-url: https://testnet-pay.crypt.bot/api/
  api-token: 377626:AAo0yQy9CN9vOBx6u3phGvrwZlDegfSqBUi

token:
  signing:
    key: q1o7M1V+7R1Qyx4e0y1m8qLC+xRP0U8UwK0QH5Xt7lQ= # JWT signing key
    lifetime: 1h
  telegram:
    bot: 7906616449:AAGLMQphhjOTHCgyAW9d9xlV94vN-Deai54 # Authentication Telegram bot token

#TODO: Disable on prod
debug: true