spring:
  application:
    name: gatewayApi

  cloud:
    gateway:
      routes:
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/auth/telegram,/auth/telegram/token,/all_users,/user_id/**,/user_role/**,/user_category/**,/save_user,/update_user/**,/delete_user/**,/categoriesById/**

        - id: adService
          uri: lb://adService
          predicates:
            - Path=/all_ads,/save_ad,/ad_delete/**,/ad_category/**,/ad_id/**,/update_ad/**

      discovery:
        locator:
          lower-case-service-id: true

server:
  port: 8990
  tomcat:
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto
    trusted-proxy: "*"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

